# Generated by Django 6.0.2 on 2026-03-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itrrequest",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="itrrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DOCUMENTS_SUBMITTED", "Documents Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("DOCUMENT_VERIFIED", "Document Verified"),
                    ("FILED", "Filed"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
