# Generated by Django 6.0.2 on 2026-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_itrrequest_razorpay_order_id_alter_document_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itrrequest",
            name="request_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
