# Generated by Django 6.0.2 on 2026-03-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_itrrequest_request_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="request",
        ),
        migrations.AddField(
            model_name="document",
            name="itr_request",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.itrrequest",
            ),
            preserve_default=False,
        ),
    ]
