# Generated by Django 6.0.2 on 2026-04-06 09:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_document_request_document_itr_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="benefits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="package",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to="documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="itrrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DOCUMENTS_SUBMITTED", "Documents Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("DOCUMENT_VERIFIED", "Document Verified"),
                    ("FILED", "Filed"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="itrrequest",
            name="service_mode",
            field=models.CharField(
                choices=[("WHATSAPP", "WhatsApp"), ("UPLOAD", "Upload")],
                default="UPLOAD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itrrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itr_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.itrrequest",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name="ITRStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DOCUMENTS_SUBMITTED", "Documents Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("DOCUMENT_VERIFIED", "Document Verified"),
                            ("FILED", "Filed"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=25,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "itr_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="core.itrrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
