# Generated by Django 6.0.2 on 2026-04-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_packages"),
        ("core", "0005_document_verification_status_package_benefits_and_more"),
    ]

    operations = []
